### ISSUE TITLE
Command failed with exit code 1: npm

### ISSUE THREAD

**Issue by parloti** [zirkelc/git-pull-run#1]
`npx git-pull-run -p "package-lock.json" -c "npm install"`

this command throws the following error

```
git-pull-run Running command 'npm' for change 'package-lock.json' in directory C:\...\...\...
error Error: Command failed with exit code 1: npm
```

the command being executed is `npm` and not `npm install`.

**Comment by zirkelc** [comment]
Hi @parloti!

That issue could be related to Windows and the working directory.

Could you run the command with --debug flag and post the entire output here?
Do you run it manually or as Husky hook?

**Comment by parloti** [comment]
I ran it as a Husky hook and manually on windows, the result is the same.

Perhaps an option, as defined [here](https://github.com/zirkelc/git-pull-run/blob/main/src/cli.ts#L24), does not accept a multiword argument.

Modifying [this line](https://github.com/zirkelc/git-pull-run/blob/main/src/runCommand.ts#L10) to `const cmdProcess = execaCommand(cmd.replace(':',' '), { cwd });`.
And running this `npx git-pull-run -p \"package-lock.json\" -c \"npm:install\" --debug` worked for me.


This is the original output, with no code change.
```
> npx git-pull-run -p "package-lock.json" -c "npm install" --debug
  git-pull-run Started git-pull-run@1.0.2 +0ms
  git-pull-run:getGitDirectory Get git directory +0ms
  git-pull-run:runGit Running git 'git rev-parse --show-toplevel' +0ms
  git-pull-run:runGit Git command executed with exit code: 0 +125ms
  git-pull-run:getGitDirectory Git directory: C:/Users/*** +127ms
  git-pull-run:getChanges Get changed files +0ms
  git-pull-run:runGit Running git 'git diff --name-only HEAD@{1} HEAD' +2ms
***
  git-pull-run:runGit Git command executed with exit code: 0 +172ms
  git-pull-run:getChanges Changed files: [***] +174ms
  git-pull-run:getChanges Match files with pattern 'package-lock.json': [ 'package-lock.json' ] +21ms
  git-pull-run Found 1 change for pattern 'package-lock.json' +0ms
  git-pull-run:getAbsolutePath Absolute path resolved: C:\Users\*** +0ms
  git-pull-run Running command 'npm' for change 'package-lock.json' in directory C:\Users\*** +2ms
  git-pull-run:runCommand Running command 'npm' in directory 'C:\Users\***' +0ms

Usage: npm <command>

where <command> is one of: ***

npm@6.14.14 C:\Program Files\nodejs\node_modules\npm
  git-pull-run:runCommand Command failed with exit code: 1 +21s
error Error: Command failed with exit code 1: npm
Debugger attached.
Waiting for the debugger to disconnect...

npm@6.14.14 C:\Program Files\nodejs\node_modules\npm
    at runCommand (file:///C:/Users/***/node_modules/git-pull-run/dist/runCommand.js:17:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async gitPullRun (file:///C:/Users/***/node_modules/git-pull-run/dist/index.js:25:32)
  git-pull-run Finished git-pull-run@1.0.2 +2m
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
/c/Program Files/nodejs/npm: line 37:   447 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"
```

**Comment by zirkelc** [comment]
@parloti thank you for your investigation so far. 

This seems to be a known problem of Node on Windows, see https://github.com/nodejs/node/issues/7367

I'm using the `execa` package to execute the commands and it suggests to escape white spaces in the command [with backslashes](https://github.com/sindresorhus/execa#execacommandcommand-options). 

> Same as [execa()](https://github.com/sindresorhus/execa#execafile-arguments-options) except both file and arguments are specified in a single command string. For example, execa('echo', ['unicorns']) is the same as execaCommand('echo unicorns').
> If the file or an argument contains spaces, they must be escaped with backslashes. 

I don't have access to a Windows machine at the moment, so I couldn't verify yet. Could you please give it a try:
`npx git-pull-run -p \"package-lock.json\" -c \"npm\ install\" --debug`

**Comment by parloti** [comment]
`npx git-pull-run -p \"package-lock.json\" -c \"npm\ install\"`

That worked like a charm.

**Comment by zirkelc** [comment]
Thank you, I'm going to add it to the README.
